# Generated by Django 5.0.9 on 2024-09-29 18:47

import django.core.validators
import django.db.models.deletion
import data_room.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0052_project_partner_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "file",
                    data_room.storage.ProtectedFileField(
                        storage=data_room.storage.ProtectedFileSystemStorage(),
                        upload_to="protected_document",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf", "gif", "png", "jpg", "jpeg", "webp"])
                        ],
                        verbose_name="File (PDF, GIF, PNG, JPG, JPEG, WEBP)",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=255)),
                ("size", models.IntegerField(default=0)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("broker", "Broker"),
                            ("partner", "Leasing partner"),
                            ("admin", "Admin"),
                        ],
                        default="client",
                        max_length=8,
                        verbose_name="User type",
                    ),
                ),
                (
                    "user_company",
                    models.CharField(max_length=1024, verbose_name="Company name"),
                ),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="protected_document-preview"),
                ),
                (
                    "reviewed",
                    models.BooleanField(default=False, verbose_name="Reviewed"),
                ),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Disabled"),
                ),
                (
                    "indexing_status",
                    models.CharField(default="pending", max_length=16, verbose_name="Indexing status"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="date_created"),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="date_updated"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protected_documents",
                        to="project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Protected Document",
                "verbose_name_plural": "Protected Documents",
                "ordering": ("name",),
            },
        ),
    ]
