# Generated by Django 5.0.9 on 2024-10-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protecteddocument",
            name="markdown",
            field=models.TextField(blank=True),
        ),
    ]
