# Generated by Django 5.0.9 on 2024-10-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0002_protecteddocument_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="protecteddocument",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
    ]
