# Generated by Django 5.1.4 on 2024-12-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0004_documenttag_protecteddocument_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="protecteddocument",
            name="use_ai",
            field=models.BooleanField(default=True, verbose_name="Use AI"),
        ),
    ]
