# Generated by Django 5.1.4 on 2025-01-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0005_protecteddocument_use_ai_protecteddocument_use_web"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protecteddocument",
            name="use_ai",
            field=models.BooleanField(default=False, verbose_name="Use AI"),
        ),
    ]
