# Generated by Django 5.1.4 on 2025-02-11 07:42

import django.core.validators
import data_room.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0006_alter_protecteddocument_use_ai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protecteddocument",
            name="file",
            field=data_room.storage.ProtectedFileField(
                max_length=255,
                storage=data_room.storage.ProtectedFileSystemStorage(),
                upload_to="protected_document",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "odt",
                            "gif",
                            "png",
                            "jpg",
                            "jpeg",
                            "webp",
                        ]
                    )
                ],
                verbose_name="File (PDF, DOCX, DOC, ODT, GIF, PNG, JPG, JPEG, WEBP)",
            ),
        ),
        migrations.AlterField(
            model_name="protecteddocument",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="protecteddocument",
            name="preview",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="protected_document-preview",
            ),
        ),
    ]
