# Generated by Django 5.1.6 on 2025-02-28 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0007_alter_protecteddocument_file_and_more"),
        ("project", "0060_alter_project_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectZip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        max_length=255,
                        upload_to="project_zips",
                        verbose_name="ZIP File",
                    ),
                ),
                (
                    "status",
                    models.CharField(default="processing", max_length=20, verbose_name="Status"),
                ),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date created"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_zips",
                        to="project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project ZIP",
                "verbose_name_plural": "Project ZIPs",
                "ordering": ("-date_created",),
            },
        ),
    ]
