# Generated by Django 5.1.6 on 2025-03-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0008_projectzip"),
    ]

    operations = [
        migrations.AddField(
            model_name="protecteddocument",
            name="indexed_chunks",
            field=models.IntegerField(default=0, verbose_name="Indexed chunks"),
        ),
    ]
