# Generated by Django 5.1.6 on 2025-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0009_protecteddocument_indexed_chunks"),
    ]

    operations = [
        migrations.AddField(
            model_name="protecteddocument",
            name="indexing_attempts",
            field=models.IntegerField(default=0, verbose_name="Indexing attempts"),
        ),
    ]
