# Generated by Django 5.1.6 on 2025-03-13 14:48

import django.core.validators
import data_room.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0010_protecteddocument_indexing_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="protecteddocument",
            name="original",
            field=data_room.storage.ProtectedFileField(
                blank=True,
                max_length=255,
                null=True,
                storage=data_room.storage.ProtectedFileSystemStorage(),
                upload_to="protected_document",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "odt",
                            "gif",
                            "png",
                            "jpg",
                            "jpeg",
                            "webp",
                        ]
                    )
                ],
                verbose_name="Original file (DOCX, DOC, ODT)",
            ),
        ),
    ]
