# Generated by Django 5.2 on 2025-05-03 16:56

import django.core.validators
import data_room.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0011_protecteddocument_original"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectzip",
            name="zip_file",
            field=data_room.storage.ProtectedFileField(
                max_length=255,
                storage=data_room.storage.ProtectedFileSystemStorage(),
                upload_to="zip",
                verbose_name="ZIP File",
            ),
        ),
        migrations.AlterField(
            model_name="protecteddocument",
            name="file",
            field=data_room.storage.ProtectedFileField(
                max_length=255,
                storage=data_room.storage.ProtectedFileSystemStorage(),
                upload_to="document",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "odt",
                            "gif",
                            "png",
                            "jpg",
                            "jpeg",
                            "webp",
                        ]
                    )
                ],
                verbose_name="File (PDF, DOCX, DOC, ODT, GIF, PNG, JPG, JPEG, WEBP)",
            ),
        ),
        migrations.AlterField(
            model_name="protecteddocument",
            name="original",
            field=data_room.storage.ProtectedFileField(
                blank=True,
                max_length=255,
                null=True,
                storage=data_room.storage.ProtectedFileSystemStorage(),
                upload_to="original",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "docx",
                            "doc",
                            "odt",
                            "gif",
                            "png",
                            "jpg",
                            "jpeg",
                            "webp",
                        ]
                    )
                ],
                verbose_name="Original file (DOCX, DOC, ODT)",
            ),
        ),
    ]
