# Generated by Django 5.2.10 on 2026-01-26 07:14

import django.core.validators
import django.db.models.deletion
import data_room.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0012_alter_projectzip_zip_file_and_more"),
        ("history", "0010_history_document"),
        ("project", "0068_project_language"),
        ("users", "0062_clientcompany_chart_of_accounts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProtectedDocument",
            new_name="ProtectedProjectDocument",
        ),
    ]
