# Generated by Django 5.2.10 on 2026-02-06 19:24

import django.core.validators
import django.db.models.deletion
import data_room.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0013_remove_protecteddocument_project_and_more"),
        ("users", "0064_add_accounting_email_to_clientcompany"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protectedprojectdocument",
            name="tag",
        ),
        migrations.AlterModelOptions(
            name="protectedprojectdocument",
            options={
                "verbose_name": "Protected Project Document",
                "verbose_name_plural": "Protected Project Documents",
            },
        ),
        migrations.AddField(
            model_name="protectedprojectdocument",
            name="company_info_json",
            field=models.JSONField(
                blank=True,
                help_text="Extracted company information as JSON",
                null=True,
                verbose_name="Company Info JSON",
            ),
        ),
        migrations.AddField(
            model_name="protectedprojectdocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("asset_specification", "Objektbeschreibung"),
                    ("offer", "Angebot"),
                    ("order_confirmation", "Auftragsbestätigung"),
                    ("invoice", "Rechnung für Objekt"),
                    ("overtaking", "Übernahmebestätigung"),
                    ("lease_contract", "Leasing-Vertrag"),
                    ("info_memo", "Info Memo"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=32,
                verbose_name="Document Type",
            ),
        ),
        migrations.AddField(
            model_name="protectedprojectdocument",
            name="file_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA256 hash for duplicate detection",
                max_length=64,
                verbose_name="File Hash (SHA256)",
            ),
        ),
        migrations.AddField(
            model_name="protectedprojectdocument",
            name="financing_object_json",
            field=models.JSONField(
                blank=True,
                help_text="Extracted financing object data as JSON",
                null=True,
                verbose_name="Financing Object JSON",
            ),
        ),
        migrations.AddField(
            model_name="protectedprojectdocument",
            name="fiscal_month",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)],
                verbose_name="Fiscal Month",
            ),
        ),
        migrations.AddField(
            model_name="protectedprojectdocument",
            name="fiscal_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Fiscal Year"),
        ),
        migrations.AddField(
            model_name="protectedprojectdocument",
            name="risk_factors_json",
            field=models.JSONField(
                blank=True, help_text="Extracted risk factors as JSON", null=True, verbose_name="Risk Factors JSON"
            ),
        ),
        migrations.AlterField(
            model_name="protectedprojectdocument",
            name="use_ai",
            field=models.BooleanField(default=True, verbose_name="Use AI"),
        ),
        migrations.AlterField(
            model_name="protectedprojectdocument",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("broker", "Broker"),
                    ("partner", "Leasing partner"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=8,
                verbose_name="Created by user type",
            ),
        ),
        migrations.CreateModel(
            name="ProtectedClientDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "file",
                    data_room.storage.ProtectedFileField(
                        max_length=255,
                        storage=data_room.storage.ProtectedFileSystemStorage(),
                        upload_to="document",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx", "doc", "odt", "gif", "png", "jpg", "jpeg", "webp"]
                            )
                        ],
                        verbose_name="File (PDF, DOCX, DOC, ODT, GIF, PNG, JPG, JPEG, WEBP)",
                    ),
                ),
                (
                    "original",
                    data_room.storage.ProtectedFileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=data_room.storage.ProtectedFileSystemStorage(),
                        upload_to="original",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx", "doc", "odt", "gif", "png", "jpg", "jpeg", "webp"]
                            )
                        ],
                        verbose_name="Original file (DOCX, DOC, ODT)",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=255)),
                ("fiscal_year", models.IntegerField(blank=True, null=True, verbose_name="Fiscal Year")),
                (
                    "fiscal_month",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Fiscal Month",
                    ),
                ),
                ("use_ai", models.BooleanField(default=True, verbose_name="Use AI")),
                ("size", models.IntegerField(default=0)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA256 hash for duplicate detection",
                        max_length=64,
                        verbose_name="File Hash (SHA256)",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("broker", "Broker"),
                            ("partner", "Leasing partner"),
                            ("admin", "Admin"),
                        ],
                        default="client",
                        max_length=8,
                        verbose_name="Created by user type",
                    ),
                ),
                ("user_company", models.CharField(max_length=1024, verbose_name="Company name")),
                (
                    "preview",
                    models.ImageField(blank=True, max_length=255, null=True, upload_to="protected_document-preview"),
                ),
                ("markdown", models.TextField(blank=True)),
                ("tokens", models.IntegerField(default=0)),
                ("reviewed", models.BooleanField(default=False, verbose_name="Reviewed")),
                ("disabled", models.BooleanField(default=False, verbose_name="Disabled")),
                ("indexing_status", models.CharField(default="pending", max_length=16, verbose_name="Indexing status")),
                ("indexing_attempts", models.IntegerField(default=0, verbose_name="Indexing attempts")),
                ("indexed_chunks", models.IntegerField(default=0, verbose_name="Indexed chunks")),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="date_created")),
                ("date_updated", models.DateTimeField(auto_now=True, verbose_name="date_updated")),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("commercial_register", "Handelsregister"),
                            ("rating", "Rating"),
                            ("annual_report", "Jahresabschluss"),
                            ("banking_facilities", "Bankenspiegel"),
                            ("business_plan", "Planzahlen"),
                            ("interim_figures", "BWA / Zwischenzahlen"),
                            ("structure_chart", "Organigramm"),
                            ("company_presentation", "Unternehmenspräsentation"),
                            ("company_description", "Unternehmensbeschreibung"),
                            ("change_concept", "Transformationskonzept"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "statement_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single Entity / Einzelabschluss"),
                            ("consolidated", "Consolidated / Konzernabschluss"),
                        ],
                        default="single",
                        max_length=15,
                        verbose_name="Statement Type",
                    ),
                ),
                ("guv_extracted", models.BooleanField(default=False, verbose_name="GuV extracted")),
                ("bilanz_extracted", models.BooleanField(default=False, verbose_name="Bilanz extracted")),
                (
                    "client_extraction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("awaiting_confirmation", "Awaiting Confirmation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=24,
                        verbose_name="Client extraction status",
                    ),
                ),
                (
                    "extracted_clients_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Temporarily stores extracted client data awaiting user confirmation",
                        verbose_name="Extracted clients data",
                    ),
                ),
                (
                    "guv_json",
                    models.JSONField(
                        blank=True, help_text="Extracted GuV data as JSON", null=True, verbose_name="GuV JSON"
                    ),
                ),
                (
                    "bilanz_json",
                    models.JSONField(
                        blank=True, help_text="Extracted Bilanz data as JSON", null=True, verbose_name="Bilanz JSON"
                    ),
                ),
                (
                    "company_info_json",
                    models.JSONField(
                        blank=True,
                        help_text="Extracted company information as JSON",
                        null=True,
                        verbose_name="Company Info JSON",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protected_documents",
                        to="users.clientcompany",
                    ),
                ),
                (
                    "linked_client",
                    models.ForeignKey(
                        blank=True,
                        help_text="The client company confirmed for this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_client_documents",
                        to="users.clientcompany",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Protected Client Document",
                "verbose_name_plural": "Protected Client Documents",
            },
        ),
        migrations.DeleteModel(
            name="DocumentTag",
        ),
    ]
