# Generated by Django 5.2.10 on 2026-03-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0015_merge_linked_client_into_client"),
        ("project", "0068_project_language"),
        ("users", "0070_alter_clientcompany_legal_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCompanyLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this company is included in Info-Memo generation for this project",
                        verbose_name="Active for Info-Memo",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="users.clientcompany",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="company_links", to="project.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Company Link",
                "verbose_name_plural": "Project Company Links",
                "unique_together": {("project", "client")},
            },
        ),
    ]
