# Generated by Django 5.2.10 on 2026-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0016_projectcompanylink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedclientdocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commercial_register", "Commercial Register"),
                    ("rating", "Rating"),
                    ("annual_report", "Annual Report"),
                    ("banking_facilities", "Banking Facilities"),
                    ("business_plan", "Business Plan"),
                    ("interim_figures", "Interim Figures"),
                    ("structure_chart", "Structure Chart"),
                    ("company_presentation", "Company Presentation"),
                    ("company_description", "Company Description"),
                    ("change_concept", "Change Concept"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
                verbose_name="Document Type",
            ),
        ),
        migrations.AlterField(
            model_name="protectedclientdocument",
            name="statement_type",
            field=models.CharField(
                blank=True,
                choices=[("single", "Single Entity"), ("consolidated", "Consolidated")],
                default="single",
                max_length=15,
                verbose_name="Statement Type",
            ),
        ),
        migrations.AlterField(
            model_name="protectedprojectdocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("asset_specification", "Asset Specification"),
                    ("offer", "Offer"),
                    ("order_confirmation", "Order Confirmation"),
                    ("invoice", "Invoice"),
                    ("overtaking", "Acceptance Confirmation"),
                    ("lease_contract", "Lease Contract"),
                    ("info_memo", "Info Memo"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
                verbose_name="Document Type",
            ),
        ),
    ]
