# Generated by Django 5.2.10 on 2026-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0017_alter_protectedclientdocument_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedclientdocument",
            name="financial_extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=24,
                verbose_name="Financial extraction status",
            ),
        ),
    ]
