# Generated by Django 5.2.10 on 2026-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0018_protectedclientdocument_financial_extraction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedprojectdocument",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=24,
                verbose_name="Extraction status",
            ),
        ),
    ]
