# Generated by Django 5.2.10 on 2026-05-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0021_drop_orphaned_accounting_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedclientdocument",
            name="json_guv_mapped",
            field=models.JSONField(
                blank=True,
                help_text="guv_json enriched with per-position aggregate roles for verification",
                null=True,
                verbose_name="GuV JSON (mapped + classified)",
            ),
        ),
    ]
