# Generated by Django 5.2.10 on 2026-05-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0022_protectedclientdocument_json_guv_mapped"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedclientdocument",
            name="pages_bilanz",
            field=models.JSONField(
                blank=True,
                help_text="1-based PDF page numbers for the Bilanz section, keyed by statement_type ('single', 'consolidated', 'notes'). Same fallback contract as pages_guv.",
                null=True,
                verbose_name="Bilanz pages (per statement_type)",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="pages_guv",
            field=models.JSONField(
                blank=True,
                help_text="1-based PDF page numbers for the GuV section, keyed by statement_type ('single', 'consolidated', 'notes'). Consumed by the Phase-4 PDF slicer; missing/empty keys trigger a full-PDF fallback.",
                null=True,
                verbose_name="GuV pages (per statement_type)",
            ),
        ),
    ]
