# Generated by Django 5.2.10 on 2026-05-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0023_protectedclientdocument_pages_bilanz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedclientdocument",
            name="accounting_framework",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AT_UGB_GKV", "AT_UGB_GKV"),
                    ("AT_UGB_UKV", "AT_UGB_UKV"),
                    ("CZ_GAAP_FUNCTION", "CZ_GAAP_FUNCTION"),
                    ("CZ_GAAP_NATURE", "CZ_GAAP_NATURE"),
                    ("DE_HGB_GKV", "DE_HGB_GKV"),
                    ("DE_HGB_UKV", "DE_HGB_UKV"),
                    ("DK_GAAP_FUNCTION", "DK_GAAP_FUNCTION"),
                    ("DK_GAAP_NATURE", "DK_GAAP_NATURE"),
                    ("IFRS_FUNCTION", "IFRS_FUNCTION"),
                    ("IFRS_NATURE", "IFRS_NATURE"),
                    ("OTHER", "OTHER"),
                ],
                help_text="Detected accounting framework code (DE_HGB_GKV / AT_UGB_GKV / IFRS_NATURE / …).",
                max_length=32,
                null=True,
                verbose_name="Accounting framework",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="accounting_framework_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Detection confidence 0.0-1.0; <0.5 logged but does not block.",
                null=True,
                verbose_name="Accounting framework confidence",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="accounting_framework_evidence",
            field=models.JSONField(
                blank=True,
                help_text="List of strings (cited indicators) that triggered detection.",
                null=True,
                verbose_name="Accounting framework evidence",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="accounting_framework_spec_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA256 of the YAML frontmatter at detection time — invalidates cached mappings.",
                max_length=64,
                null=True,
                verbose_name="Accounting framework spec_hash",
            ),
        ),
    ]
