# Generated by Django 5.2.10 on 2026-05-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0024_accounting_framework_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedclientdocument",
            name="json_guv_mapped_v2_preview",
            field=models.JSONField(
                blank=True,
                help_text="Stage-3 shadow cache for the v2 spec-driven compiler. v1 reader/writer ignores it. Stage 4 cutover flips v2 to main `json_guv_mapped`; Stage 5 drops this field.",
                null=True,
                verbose_name="GuV mapping (v2 preview, shadow field)",
            ),
        ),
    ]
