# Generated by Django 5.2.10 on 2026-05-07 15:31

from django.db import migrations, models


def _backfill_review_status_disabled(apps, schema_editor):
    """Existing documents predate the review loop. Mark them
    `disabled` instead of leaving them at the new default `pending`,
    so the UI does not show all of them as "in progress" forever
    while the feature flag is off."""
    Doc = apps.get_model("data_room", "ProtectedClientDocument")
    Doc.objects.filter(review_status="pending").update(review_status="disabled")


def _noop(apps, schema_editor):
    """Reverse: keep `disabled` as-is (data is informative, not destructive)."""


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0025_v2_preview_shadow_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedclientdocument",
            name="json_aggregate",
            field=models.JSONField(
                blank=True,
                help_text="Flat single-fiscal-year aggregate computed by the Self-Review-Loop. Audit/review artefact only — the memo renderer ignores this field.",
                null=True,
                verbose_name="Per-doc aggregate snapshot (review-only)",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="json_bilanz_pre_review_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Run-0 Bilanz extraction frozen for the current review_cycle_id.",
                null=True,
                verbose_name="Bilanz pre-review snapshot",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="json_guv_mapped_pre_review_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Run-0 mapping frozen for the current review_cycle_id.",
                null=True,
                verbose_name="Mapped GuV pre-review snapshot",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="json_guv_pre_review_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Run-0 GuV extraction frozen for the current review_cycle_id.",
                null=True,
                verbose_name="GuV pre-review snapshot",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="pre_review_snapshot_meta",
            field=models.JSONField(
                blank=True,
                help_text="{cycle_id, frozen_at, extraction_model, prompt_version} stamped at first freeze of the cycle.",
                null=True,
                verbose_name="Pre-review snapshot meta",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="review_cycle_id",
            field=models.UUIDField(
                blank=True,
                help_text="Per-cycle UUID. Re-uploading or force-reprocessing starts a new cycle and freezes new pre_review_snapshots.",
                null=True,
                verbose_name="Review cycle id",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="review_runs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-iteration audit records: hard-check findings, LLM review result, combined_score, tokens, selected_as_best.",
                verbose_name="Review-Loop audit trail",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="review_score",
            field=models.FloatField(
                blank=True,
                help_text="0.0–1.0 weighted score of the best iteration.",
                null=True,
                verbose_name="Review-Loop combined score",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("processing", "processing"),
                    ("passed", "passed"),
                    ("failed", "failed"),
                    ("skipped", "skipped"),
                    ("disabled", "disabled"),
                    ("invalid_review_output", "invalid_review_output"),
                ],
                default="pending",
                help_text="State of the upload-time Self-Review-Loop for this doc.",
                max_length=24,
                verbose_name="Review-Loop status",
            ),
        ),
        migrations.RunPython(
            _backfill_review_status_disabled,
            reverse_code=_noop,
        ),
    ]
