# Generated by Django 5.2.10 on 2026-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0026_review_loop_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedclientdocument",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("queued", "queued"),
                    ("processing", "processing"),
                    ("passed", "passed"),
                    ("failed", "failed"),
                    ("skipped", "skipped"),
                    ("disabled", "disabled"),
                    ("invalid_review_output", "invalid_review_output"),
                ],
                default="pending",
                help_text="State of the upload-time Self-Review-Loop for this doc.",
                max_length=24,
                verbose_name="Review-Loop status",
            ),
        ),
    ]
