# Generated by Django 5.2.10 on 2026-05-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_room", "0027_review_status_queued_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedclientdocument",
            name="bilanz_mapping_status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("mapping_missing", "Mapping missing"),
                    ("re_mapping", "Re-mapping in progress"),
                    ("re_mapping_failed", "Re-mapping failed"),
                    ("not_applicable", "Not applicable"),
                    ("stamp_registry_mismatch", "Display-Stamp registry version mismatch"),
                ],
                db_index=True,
                default="mapping_missing",
                max_length=32,
                verbose_name="Bilanz mapping status",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="guv_mapping_status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("mapping_missing", "Mapping missing"),
                    ("re_mapping", "Re-mapping in progress"),
                    ("re_mapping_failed", "Re-mapping failed"),
                    ("not_applicable", "Not applicable"),
                    ("stamp_registry_mismatch", "Display-Stamp registry version mismatch"),
                ],
                db_index=True,
                default="mapping_missing",
                max_length=32,
                verbose_name="GuV mapping status",
            ),
        ),
        migrations.AddField(
            model_name="protectedclientdocument",
            name="json_bilanz_mapped",
            field=models.JSONField(
                blank=True,
                help_text="Per-doc Bilanz-Slot-Mapping (Phase A scope: slot-based). Populated at upload time.",
                null=True,
                verbose_name="Bilanz JSON (mapped to slots)",
            ),
        ),
    ]
